Name: Initial Config
ignoreDependencies: false
VlocityDataPackKeys:
    - CpqConfigurationSetup/AddPromoValidate
    - CpqConfigurationSetup/AllowOperationsOnDiscProducts
    - CpqConfigurationSetup/AlwaysInsertMessageElement
    - CpqConfigurationSetup/ApplyPromoToBundleWithExpiredChildItem
    - CpqConfigurationSetup/Attribute Check Mode
    - CpqConfigurationSetup/AttributeValueDisplaySortMode
    - CpqConfigurationSetup/CacheAPI.BasketAPIPoolSize
    - CpqConfigurationSetup/CacheAPI.CombinationLimit
    - CpqConfigurationSetup/CacheAPI.CreateCartBatchSize
    - CpqConfigurationSetup/CacheAPI.CreateCartFromContextKey
    - CpqConfigurationSetup/CacheAPI.CustomGroupContextItems
    - CpqConfigurationSetup/CacheAPI.DeletePseudoRecords
    - CpqConfigurationSetup/CacheAPI.ExternalSystemAuthHeader
    - CpqConfigurationSetup/CacheAPI.ExternalSystemPartitionKey
    - CpqConfigurationSetup/CacheAPI.ExternalSystemURL
    - CpqConfigurationSetup/CacheAPI.GenericOffersAttribute
    - CpqConfigurationSetup/CacheAPI.GetOffersCacheRecLimit
    - CpqConfigurationSetup/CacheAPI.GetOffersVerCacheRecLimit
    - CpqConfigurationSetup/CacheAPI.GetRelOffersCacheRecComLimit
    - CpqConfigurationSetup/CacheAPI.GetRelOffersCacheRecLimit
    - CpqConfigurationSetup/CacheAPI.IncludeParentContextPLEs
    - CpqConfigurationSetup/CacheAPI.MaxCombinationLimit
    - CpqConfigurationSetup/CacheAPI.MaxGetOffersCacheRecLimit
    - CpqConfigurationSetup/CacheAPI.MaxGetRelOffersCacheRecLimit
    - CpqConfigurationSetup/CacheAPI.OptimizedBasketResponse
    - CpqConfigurationSetup/CacheAPI.PerfMode
    - CpqConfigurationSetup/CacheAPI.RegenerateBasket
    - CpqConfigurationSetup/CacheAPI.RegenerateBatchCacheProcessor
    - CpqConfigurationSetup/CacheAPI.RegenerateCatalogBatches
    - CpqConfigurationSetup/CacheAPI.RegenerateEntriesPartition
    - CpqConfigurationSetup/CacheAPI.RegenerateFutureDatedCache
    - CpqConfigurationSetup/CacheAPI.RemoveNonCacheableAttribInDCG
    - CpqConfigurationSetup/CacheAPI.SkinnyBasket
    - CpqConfigurationSetup/CacheAPI.SkinnyCtxDmsnCombinations
    - CpqConfigurationSetup/CacheAPI.TimeToLiveInDays
    - CpqConfigurationSetup/CacheAPI.TrimMode
    - CpqConfigurationSetup/CacheAPIFields
    - CpqConfigurationSetup/CacheAPIPartialConfigure
    - CpqConfigurationSetup/CacheAPIPartialConfigureProduct
    - CpqConfigurationSetup/CachedQueryMode
    - CpqConfigurationSetup/CacheEnabled
    - CpqConfigurationSetup/Cart Customizable Attribute Level
    - CpqConfigurationSetup/Cart Level Discount Approval Required
    - CpqConfigurationSetup/ConfigurationSnapshotLock
    - CpqConfigurationSetup/ContextRulesCacheMode
    - CpqConfigurationSetup/ContextRulesEnabled
    - CpqConfigurationSetup/ControlProduct2FieldsDuringCreation
    - CpqConfigurationSetup/CPQ Cart Preview Modal Use API
    - CpqConfigurationSetup/CPQ Toast Message Log Level
    - CpqConfigurationSetup/CpqCachePvtKey
    - CpqConfigurationSetup/CpqNextPricingPlan
    - CpqConfigurationSetup/CreateAdjForAbsZeroValue
    - CpqConfigurationSetup/CustomRuleMessageFieldName
    - CpqConfigurationSetup/DefaultAccountFieldset
    - CpqConfigurationSetup/DefaultEntityFilterEditFieldset
    - CpqConfigurationSetup/DefaultHierarchy
    - CpqConfigurationSetup/DefaultPowerUpdateJobThreshold
    - CpqConfigurationSetup/DefaultPricingPlan
    - CpqConfigurationSetup/DefaultSplitJobThreshold
    - CpqConfigurationSetup/DeleteServices
    - CpqConfigurationSetup/DeltaPrice
    - CpqConfigurationSetup/DeltaValidate
    - CpqConfigurationSetup/EnableMultiServiceBulkAction
    - CpqConfigurationSetup/EnableSupplementalOrderPricing
    - CpqConfigurationSetup/EnableUserNotifier
    - CpqConfigurationSetup/EnforceOfferMigrationOfferTypeMatch
    - CpqConfigurationSetup/ExcludedCatalogProductDefinitionJobs
    - CpqConfigurationSetup/FDOStatuses
    - CpqConfigurationSetup/FilterRuleWithEligAvail
    - CpqConfigurationSetup/FindReferencesRowCountLimit
    - CpqConfigurationSetup/GuestHandlingEnabled
    - CpqConfigurationSetup/ImplicitPricing
    - CpqConfigurationSetup/ImplicitSaveMode
    - CpqConfigurationSetup/IncludeAddOnsAttributes
    - CpqConfigurationSetup/LevelBasedApproach
    - CpqConfigurationSetup/LevelBasedPageSize
    - CpqConfigurationSetup/LevelBasedPagination
    - CpqConfigurationSetup/LockOrderAfterSubmitToOM
    - CpqConfigurationSetup/LogOdinNotifications
    - CpqConfigurationSetup/MarginCalculationType
    - CpqConfigurationSetup/MaxCPUTimePerTransaction
    - CpqConfigurationSetup/MaxHeapSizePerTransaction
    - CpqConfigurationSetup/MTSEnabled
    - CpqConfigurationSetup/Multiple Promotion Nodes Resolution
    - CpqConfigurationSetup/MultiServiceMasterOrderRecordTypes
    - CpqConfigurationSetup/MultiServiceMasterQuoteRecordTypes
    - CpqConfigurationSetup/MultiServiceSingleOrderRecordTypes
    - CpqConfigurationSetup/MultiServiceSingleQuoteRecordTypes
    - CpqConfigurationSetup/NeedContextForAttribConfig
    - CpqConfigurationSetup/NumberOfDMLPerTransaction
    - CpqConfigurationSetup/NumberOfQueriesPerTransaction
    - CpqConfigurationSetup/ObjectCopierPrice
    - CpqConfigurationSetup/ObjectCopierValidate
    - CpqConfigurationSetup/OrderItemIgnoredColumns
    - CpqConfigurationSetup/OriginalOrderCancellationStatusChanges
    - CpqConfigurationSetup/PaginationSize
    - CpqConfigurationSetup/PopulateAllActionVariants
    - CpqConfigurationSetup/PreventNegativeAdjustment
    - CpqConfigurationSetup/PriceBookRefreshBatchSize
    - CpqConfigurationSetup/PricingElementServiceLogging
    - CpqConfigurationSetup/PricingPlanServiceLogging
    - CpqConfigurationSetup/Product Configuration Mode
    - CpqConfigurationSetup/ProductAttribJSONBatchJob Update All
    - CpqConfigurationSetup/ProductAttributesBatchProcessorSize
    - CpqConfigurationSetup/ProductEligibilityDisplayAll
    - CpqConfigurationSetup/ProductEligibilityMatrixLogging
    - CpqConfigurationSetup/ProductHierarchyBatchProcessorSize
    - CpqConfigurationSetup/RetainRecurringPriceDisconnectOrCancel
    - CpqConfigurationSetup/RollupActionCodeField
    - CpqConfigurationSetup/RunPCPInPostExecuteMethod
    - CpqConfigurationSetup/SaveProductAttribMetadataCache
    - CpqConfigurationSetup/SaveProductAttributeMetadata
    - CpqConfigurationSetup/ShouldConsiderDeletedItems
    - CpqConfigurationSetup/SimplePLERuleCacheMode
    - CpqConfigurationSetup/SingleFdoMode
    - CpqConfigurationSetup/Standard Pricing Plan
    - CpqConfigurationSetup/StrictSplitModeEnabled
    - CpqConfigurationSetup/Toggle Next Message Flag
    - CpqConfigurationSetup/UseAssetReferenceIdForParentAndRoot
    - CpqConfigurationSetup/UseWeights
    - CpqConfigurationSetup/UsingPromotions
    - CpqConfigurationSetup/UsingWeights
    - CpqConfigurationSetup/ValidateAndUpgradeV2Attributes
    - InterfaceImplementation/ABOAssetInterface
    - InterfaceImplementation/AccountContextInterface
    - InterfaceImplementation/ActivateFrameContractInterface
    - InterfaceImplementation/AddPricebookEntryInterface
    - InterfaceImplementation/AddProductInterface
    - InterfaceImplementation/ApprovalProcessInterface
    - InterfaceImplementation/ApprovalStatusInterface
    - InterfaceImplementation/AssetFilterInterface
    - InterfaceImplementation/AssetsContextInterface
    - InterfaceImplementation/AttributeGUIDBatchJobQuery
    - InterfaceImplementation/BillingProfileInterface
    - InterfaceImplementation/BulkXLIEditInterface
    - InterfaceImplementation/BundleContextInterface
    - InterfaceImplementation/CacheableFDO
    - InterfaceImplementation/CachedAPIResponse
    - InterfaceImplementation/CachedBasketPricerInterface
    - InterfaceImplementation/CachePopulation
    - InterfaceImplementation/CalculateUnitPriceInterface
    - InterfaceImplementation/CartContextInterface
    - InterfaceImplementation/CategoryGUIDBatchJobQuery
    - InterfaceImplementation/ChildItemSelectionInterface
    - InterfaceImplementation/CloneAdditionalObjects
    - InterfaceImplementation/CloneFieldListInterface
    - InterfaceImplementation/CMAttributeAssignmentInterface
    - InterfaceImplementation/CMCalculationMatrixRowInterface
    - InterfaceImplementation/CMCatalogInterface
    - InterfaceImplementation/CMCatalogProductRelationshipInterface
    - InterfaceImplementation/CMContextDimensionInterface
    - InterfaceImplementation/CMEntityFilterConditionInterface
    - InterfaceImplementation/CMEntityFilterInterface
    - InterfaceImplementation/CMPriceListEntryInterface
    - InterfaceImplementation/CMProduct2Interface
    - InterfaceImplementation/CMProductChildItemInterface
    - InterfaceImplementation/CMProductConfigurationProcedureInterface
    - InterfaceImplementation/CMProductRelationshipInterface
    - InterfaceImplementation/CMPromotionInterface
    - InterfaceImplementation/CMPromotionItemInterface
    - InterfaceImplementation/CMRuleAssignmentInterface
    - InterfaceImplementation/CMRuleInterface
    - InterfaceImplementation/CMVlocityAttachmentInterface
    - InterfaceImplementation/ContextDimensionMapperInterface
    - InterfaceImplementation/ContextEligibilityBatchJobRecord
    - InterfaceImplementation/ContextInputParserInterface
    - InterfaceImplementation/ContextRuleService
    - InterfaceImplementation/ContractContextInterface
    - InterfaceImplementation/ContractStateModelInterface
    - InterfaceImplementation/CpqAppHandler
    - InterfaceImplementation/CpqCalcMatrixRowSelectorInterface
    - InterfaceImplementation/CpqCalcMatrixVersionSelectorInterface
    - InterfaceImplementation/CPQCartCheckoutMessages
    - InterfaceImplementation/CpqPricingPlanStepSelectorInterface
    - InterfaceImplementation/CPQSubmitFlowInterface
    - InterfaceImplementation/CreateCart
    - InterfaceImplementation/CtxRulesPriceElementsOpenInterface
    - InterfaceImplementation/CtxRulesPriceListsOpenInterface
    - InterfaceImplementation/DataProfileBatchJobRecord
    - InterfaceImplementation/DCProductVersionBatchJobRecord
    - InterfaceImplementation/DCPromoVersionBatchJobRecord
    - InterfaceImplementation/DCTimeSliceListBatchJobRecord
    - InterfaceImplementation/DCTimeSlicesGeneratorBatchJobRecord
    - InterfaceImplementation/DCVersionInfoListBatchJobRecord
    - InterfaceImplementation/DeleteProductInterface
    - InterfaceImplementation/DiscountActivation
    - InterfaceImplementation/DiscountSelector
    - InterfaceImplementation/EligibilityContextInterface
    - InterfaceImplementation/FieldMapperInterface
    - InterfaceImplementation/FollowOnForAmend
    - InterfaceImplementation/FrameContractDiscountInterface
    - InterfaceImplementation/FreezeOrdAcceptedResponse
    - InterfaceImplementation/FreezeOrdRejectedResponse
    - InterfaceImplementation/GetConditionalTemplateItemsInterface
    - InterfaceImplementation/GetConditionalTemplateSectionsInterface
    - InterfaceImplementation/GetContractSignatureRequiredInterface
    - InterfaceImplementation/GetContractTemplateNameInterface
    - InterfaceImplementation/GetContractTermInterface
    - InterfaceImplementation/GetDocTemplateNameInterface
    - InterfaceImplementation/GetDocumentTemplateListInterface
    - InterfaceImplementation/GetFrameContractQueryWhereClauseInterface
    - InterfaceImplementation/GetItemsListInterface
    - InterfaceImplementation/GetOfferDetailsBatchJobRecord
    - InterfaceImplementation/GetOffersBatchJobRecord
    - InterfaceImplementation/GetOffersHierarchyBatchJobRecord
    - InterfaceImplementation/GetOffersItemBatchJobRecord
    - InterfaceImplementation/GetPricesBatchJobRecord
    - InterfaceImplementation/GetProductListInterface
    - InterfaceImplementation/GetRelatedOffersBatchJobRecord
    - InterfaceImplementation/GetUpdateContractListInterface
    - InterfaceImplementation/GroupContextInterface
    - InterfaceImplementation/GUIDGenerator
    - InterfaceImplementation/InsertMediaPrintIssues
    - InterfaceImplementation/IsContractDocumentEditableInterface
    - InterfaceImplementation/KeyUpdatableInterface
    - InterfaceImplementation/LandingPageSelectorInterface
    - InterfaceImplementation/LoadConfiguration
    - InterfaceImplementation/MakeParentProductInterface
    - InterfaceImplementation/MarginRangeLoader
    - InterfaceImplementation/MarginValidation
    - InterfaceImplementation/MSApplyToGroupInterface
    - InterfaceImplementation/MSMemberObjectSelector
    - InterfaceImplementation/MyInvoicesInterface
    - InterfaceImplementation/NewProductVersionInterface
    - InterfaceImplementation/ObjectCopierInterface
    - InterfaceImplementation/OdinAPIHandler
    - InterfaceImplementation/OdinAttributeFormatter
    - InterfaceImplementation/OdinClassifyResponse
    - InterfaceImplementation/OdinNotifFldFormatInterface
    - InterfaceImplementation/OdinNotificationClassifier
    - InterfaceImplementation/OdinOrderAccepted
    - InterfaceImplementation/OdinOrderActivated
    - InterfaceImplementation/OdinOrderInProgress
    - InterfaceImplementation/OdinOrderItemAccepted
    - InterfaceImplementation/OdinOrderItemActivated
    - InterfaceImplementation/OdinOrderItemAssetize
    - InterfaceImplementation/OdinOrderItemInProgress
    - InterfaceImplementation/OdinOrderItemRejected
    - InterfaceImplementation/OdinOrderQueued
    - InterfaceImplementation/OdinOrderRejected
    - InterfaceImplementation/OdinSubmitOrderExtraFields
    - InterfaceImplementation/OdinValidator
    - InterfaceImplementation/OpportunityContractFlagRollupInterface
    - InterfaceImplementation/OpptyScheduleInterface
    - InterfaceImplementation/OrderContractFlagRollupInterface
    - InterfaceImplementation/PostChangeHandlerInterface
    - InterfaceImplementation/PreConfigureHandlerInterface
    - InterfaceImplementation/PremisesInterface
    - InterfaceImplementation/PricebookDefaultInterface
    - InterfaceImplementation/PricingInterface
    - InterfaceImplementation/PricingManAdjEligibilityInterface
    - InterfaceImplementation/PricingSelectorInterface
    - InterfaceImplementation/ProcessBillingInterface
    - InterfaceImplementation/ProductAvailabilityInterface
    - InterfaceImplementation/ProductAvailabilityOpenInterface
    - InterfaceImplementation/ProductDefinitionInterface
    - InterfaceImplementation/ProductEligibilityInterface
    - InterfaceImplementation/ProductEligibilityOpenInterface
    - InterfaceImplementation/ProductSelectorInterface
    - InterfaceImplementation/ProductValidationInterface
    - InterfaceImplementation/PromotionWrapperBatchJobRecord
    - InterfaceImplementation/QueuedOrderSelector
    - InterfaceImplementation/QuoteContractFlagRollupInterface
    - InterfaceImplementation/RenewContractBatchJobProcessInterface
    - InterfaceImplementation/RenewContractBatchJobQueryInterface
    - InterfaceImplementation/RepricingInterface
    - InterfaceImplementation/RepricingLineItemSelectorInterface
    - InterfaceImplementation/RepricingManAdjEligibilityInterface
    - InterfaceImplementation/ResolveRefDate
    - InterfaceImplementation/RESTCPQInterface
    - InterfaceImplementation/RuleSetCombinationBatchJobRecord
    - InterfaceImplementation/RuleSetCombinationBatchJobRecord
    - InterfaceImplementation/SendFreezeToOM
    - InterfaceImplementation/SendSubmitToOM
    - InterfaceImplementation/SendUnfreezeToOM
    - InterfaceImplementation/SetUsageQuantity
    - InterfaceImplementation/SimplePromoSelector
    - InterfaceImplementation/SplitProductInterface
    - InterfaceImplementation/SubmitOrdAcceptedResponse
    - InterfaceImplementation/SubmitOrdProvAcceptedResponse
    - InterfaceImplementation/SubmitOrdRejectedResponse
    - InterfaceImplementation/SupplementalOrderService
    - InterfaceImplementation/SupplementForAmend
    - InterfaceImplementation/SupplementForCancel
    - InterfaceImplementation/SyncQuoteToOpptyInterface
    - InterfaceImplementation/SyncXLIs
    - InterfaceImplementation/TightestMatchInterface
    - InterfaceImplementation/TimePolicyInterface
    - InterfaceImplementation/TransactionContextInterface
    - InterfaceImplementation/UnfreezeOrdAcceptedResponse
    - InterfaceImplementation/UnfreezeOrdRejectedResponse
    - InterfaceImplementation/UnparentProductInterface
    - InterfaceImplementation/UpdateFrameContractInterface
    - InterfaceImplementation/UpdateProductInterface
    - InterfaceImplementation/UsageConfigLoader
    - InterfaceImplementation/UserContextInterface
    - InterfaceImplementation/UserNotifier
    - InterfaceImplementation/V3BasketXLI
    - InterfaceImplementation/V3CachedAPISelector
    - InterfaceImplementation/V3CachedResponse
    - InterfaceImplementation/V3CacheKeyGeneration
    - InterfaceImplementation/V3CachingService
    - InterfaceImplementation/V3CreateCartFromPool
    - InterfaceImplementation/V3PoolOrderSelector
    - InterfaceImplementation/V3PrepareResponse
    - InterfaceImplementation/V3PromotionService
    - InterfaceImplementation/V3PromotionWrapperService
    - InterfaceImplementation/V3QuerySelector
    - InterfaceImplementation/ValidateAddressInterface
    - InterfaceImplementation/ValidateModifyMediaPlan
    - InterfaceImplementation/XOMSupplementalOrderLifeCycle
    - PricingPlan/Default Pricing Plan
    - Product2/9f774185-dafa-7775-93d8-20693277f221
    - Product2/55628b66-7484-3374-82a2-86f4cc74c608
    - Product2/cce158b7-6247-8105-89d9-b85f0c11af35
    - Product2/c0162659-f005-f459-1ef7-7a5fb41958a1
    - Product2/5b302f2f-b179-24fa-572b-b88ce6eb57d0
    - Product2/5a131693-0f2a-682c-2daf-8142efe03e1e
    - Product2/6dd880ef-77bd-fb4e-c327-e8d35f1fae04
    - Product2/23ab466e-7783-c76d-5ecc-1335e8ccee58
    - Product2/1921ae06-07d0-29e7-f282-fbaea6d05782
    - Product2/4898ab00-a47b-5804-9cbb-b12a54bbb3dd
    - Product2/698a0c5f-65ff-2480-6f9e-9458724ddbb1
    - Product2/4c6cd2a1-e567-6cde-8c74-3ac270cf8c10
    - Product2/4af4f47c-1753-836b-a777-e3b9c98665c9
    - Product2/9310fdc5-abbc-7b32-5658-af9caf4b6962
    - Product2/11b1105a-a724-11d3-fdc3-1acedf614a1f
    - Product2/7e2bb73a-c03c-33d5-b11e-88de21d7448c
    - Product2/8a27b64c-4ead-c3cc-645b-11c53dea6da4
    - Product2/8719f803-021c-f517-c2d0-e78fa4f32c9a
    - Product2/5958ed63-caa3-6fe2-c6c5-496fdea3d1e0
    - Product2/66f275a8-a0c8-5c2f-5db3-8e1b299fbb01
    - Product2/6e5fb23d-5255-5950-8b9d-b0845a86ea57
    - Product2/462b7e10-73f1-234f-22d9-129c971e0000
    - Product2/0232f236-280b-29af-1de7-2279e005c759
    - Product2/3b01419f-a13a-18b0-e7a0-306b73f753ab
    - Product2/8230938e-c169-b111-8174-3af7091cfb41
    - Product2/2a2f352e-4592-2263-c16f-eb9fc5a1751d
    - Product2/b831d966-69ce-7291-a824-a6e7ca4f0afd
    - Product2/32e5b137-77e5-3a28-360e-d338d807e0e0
    - Product2/a77cf99c-cde9-48ea-e27c-c89fd9ad8797
    - Product2/66126081-307c-09cc-cdca-b6e3270d3a1d
    - Product2/89a38e45-d28e-0b75-4c95-4abe90f58bdb
    - Product2/906c56ab-ffab-9edb-fa4e-e0f8bc837e18
    - Product2/da4d6803-e0ff-068b-bc10-6e72d06a10b8
    - Product2/9671c95d-cbd4-bb0a-a4c9-20bea7a8306d
    - Product2/9e068ff7-70b0-3bda-5dca-cc563734f7e4
    - Product2/7cc4a4e4-67f8-3e0e-0d54-28689645c715
    - Product2/d5bde9e6-7e34-e641-02e0-6a7a1b65431b
    - Product2/fa05e802-3c00-3040-6114-db1ee0e90297
VlocityTypesToFetch:
    - CpqConfigurationSetup
    - InterfaceImplementation
    - PricingPlan
    - Product2
SalesforceTypesToFetch:
